PACKET_SIZE = 1500
NODE_IDX = 0
PORT = "8300"
NEIGHBORS = ["172.19.0.100", "172.19.0.103", "172.19.0.108", "172.19.0.109", "172.19.0.110", "172.19.0.112", "172.19.0.117", "172.19.0.118", "172.19.0.119", "172.19.0.121", "172.19.0.126", "172.19.0.127", "172.19.0.128", "172.19.0.130", "172.19.0.135", "172.19.0.136", "172.19.0.137", "172.19.0.139", "172.19.0.144", "172.19.0.145", "172.19.0.146", "172.19.0.148", "172.19.0.153", "172.19.0.154", "172.19.0.155", "172.19.0.157", "172.19.0.162", "172.19.0.163", "172.19.0.164", "172.19.0.166", "172.19.0.171", "172.19.0.172", "172.19.0.173", "172.19.0.175", "172.19.0.180", "172.19.0.181", "172.19.0.182", "172.19.0.184", "172.19.0.189", "172.19.0.190", "172.19.0.191", "172.19.0.193", "172.19.0.198", "172.19.0.199" ]
MAX_BLOCK = 5
BLOCK_GEN_TIME = 1000
PULL_INTERVAL = 4000
BLOCK_FILE = "block_50KB"
ONLY_PUSH = false
F_OUT = 1