PACKET_SIZE=1500
NODE_IDX=0
PORT=8300
NEIGHBORS="172.19.0.101,172.19.0.102,172.19.0.103,172.19.0.104,172.19.0.105,172.19.0.106,172.19.0.107,172.19.0.108,172.19.0.109,172.19.0.110,172.19.0.111,172.19.0.112,172.19.0.113,172.19.0.114,172.19.0.115,172.19.0.116,172.19.0.117,172.19.0.118"
MAX_BLOCK=100
BLOCK_GEN_TIME=1000
PULL_INTERVAL=4000
BLOCK_FILE="block_50KB"
ONLY_PUSH=false
F_OUT=3
PROTOCOL="UDP"